#services:
#  mysql:
#    image: mysql:8.3.0
#    container_name: my_sql
#    environment:
#      MYSQL_ROOT_PASSWORD: mysql
#      MYSQL_DATABASE: order_service
#    ports:
#      - "3307:3306"
#    volumes:
#      - ./mysql:/var/lib/mysql
#      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql

services:
  mysql:
    image: mysql:8.3.0
    container_name: my_sql
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: order_service   # âœ… REQUIRED
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  mysql_data:
