services:
  mysql:
    image: mysql:8.3.0
    container_name: inventory_mysql
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: inventory_service
    volumes:
      - inventory_mysql_data:/var/lib/mysql
      #- ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  inventory_mysql_data:

#services:
#  mysql:
#    image: mysql:8.3.0
#    container_name: my_sql
#    environment:
#      MYSQL_ROOT_PASSWORD: mysql
#      MYSQL_DATABASE: order_service
#    ports:
#      - "3307:3306"
#    volumes:
#      - ./mysql:/var/lib/mysql
#      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql


#////////////////
#version: '3.8'
#services:
#  mysql:
#    image: mysql:8.3.0
#    container_name: mysql
#    ports:
#      - "3308:3306"
#    environment:
#      MYSQL_ROOT_PASSWORD: mysql
#    volumes:
#      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
#      - ./docker/mysql/data:/var/lib/mysql
#    healthcheck:
#      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
#      interval: 5s
#      timeout: 5s
#      retries: 10